version: '3'

volumes:
  pgdata:

services:
  api:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '80:80'

  postgres:
    image: 'postgres:14.1'
    env_file:
      - config/.env
    ports:
          - "5431:5432"