[tool.poetry]
name = "tapas"
version = "0.1.0"
description = ""
authors = ["nanoastax <jakub.kramp@profil-software.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.89.1"
sqlmodel = "^0.0.8"
uvicorn = "^0.20.0"
alembic = "^1.9.3"
psycopg2-binary = "^2.9.5"
django-environ = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
