"""Added ingredient items

Revision ID: 17ef3d59234c
Revises: ca22444c1de5
Create Date: 2023-03-16 15:30:39.990424

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '17ef3d59234c'
down_revision = 'ca22444c1de5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
