"""Initial migration

Revision ID: 1ae8633d956b
Revises: 
Create Date: 2026-02-26 01:56:35.697100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae8633d956b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    op.drop_table('profile')
    op.drop_table('ingredientitem')
    op.drop_table('dish')
    op.drop_table('user')
    # ### end Alembic commands ###


def upgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('password', name=op.f('user_password_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('dish',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recipe', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dish_pkey'))
    )
    op.create_table('ingredient',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fat_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fat_saturated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('protein', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sodium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('potassium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cholesterol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('carbohydrates_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fiber', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sugar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ingredient_pkey')),
    sa.UniqueConstraint('name', name=op.f('ingredient_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ingredientitem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], name=op.f('ingredientitem_dish_id_fkey')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('ingredientitem_ingredient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingredientitem_pkey'))
    )
    op.create_table('profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activity_factor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('smoking', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('carbohydrates', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protein', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fiber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('potassium', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sodium', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('profile_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_pkey'))
    )
    # ### end Alembic commands ###
