"""Created profile

Revision ID: 45016b1511cc
Revises: b3a7f62d05f4
Create Date: 2023-04-17 15:50:39.822222

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "45016b1511cc"
down_revision = "b3a7f62d05f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
