"""Created fridge models

Revision ID: 49e0efb25571
Revises: 1ae8633d956b
Create Date: 2026-02-26 20:40:24.000172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49e0efb25571'
down_revision: Union[str, Sequence[str], None] = '1ae8633d956b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('little', 'one_time', 'two_times', 'three_times', 'every_day', 'professional_athlete', name='activityfactor').create(op.get_bind())
    sa.Enum('MALE', 'FEMALE', name='sexenum').create(op.get_bind())
    op.create_table('fridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.Column('marked_for_delete', sa.Boolean(), nullable=False),
    sa.Column('fridge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fridge_id'], ['fridge.id'], ),
    sa.ForeignKeyConstraint(['id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('profile', 'sex',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('MALE', 'FEMALE', name='sexenum'),
               existing_nullable=False,
               postgresql_using='sex::sexenum')
    op.alter_column('profile', 'activity_factor',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('little', 'one_time', 'two_times', 'three_times', 'every_day', 'professional_athlete', name='activityfactor'),
               nullable=False,
               postgresql_using='activity_factor::activityfactor')
    op.alter_column('profile', 'calories',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profile', 'carbohydrates',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profile', 'fat',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profile', 'protein',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profile', 'fiber',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profile', 'potassium',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('profile', 'sodium',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(op.f('user_password_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_password_key'), 'user', ['password'], postgresql_nulls_not_distinct=False)
    op.alter_column('profile', 'sodium',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profile', 'potassium',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profile', 'fiber',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profile', 'protein',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profile', 'fat',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profile', 'carbohydrates',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profile', 'calories',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('profile', 'activity_factor',
               existing_type=postgresql.ENUM('little', 'one_time', 'two_times', 'three_times', 'every_day', 'professional_athlete', name='activityfactor'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profile', 'sex',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='sexenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('product')
    op.drop_table('fridge')
    sa.Enum('MALE', 'FEMALE', name='sexenum').drop(op.get_bind())
    sa.Enum('little', 'one_time', 'two_times', 'three_times', 'every_day', 'professional_athlete', name='activityfactor').drop(op.get_bind())
    # ### end Alembic commands ###
