"""Added images

Revision ID: 6b0b686f3fc2
Revises: 4e40f5bd2f1c
Create Date: 2026-03-04 23:08:44.715151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0b686f3fc2'
down_revision: Union[str, Sequence[str], None] = '4e40f5bd2f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index('unique_dish_main_picture', 'images', ['dish_id'], unique=True, postgresql_where=sa.text('is_main = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_dish_main_picture', table_name='images', postgresql_where=sa.text('is_main = true'))
    op.drop_table('images')
    # ### end Alembic commands ###
