"""Removed DRI model

Revision ID: 7e72dbe92283
Revises: a507345d73fb
Create Date: 2023-04-26 11:23:53.841487

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "7e72dbe92283"
down_revision = "a507345d73fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile",
        sa.Column(
            "activity_factor",
            sqlalchemy_utils.types.choice.ChoiceType(choices=["ah", "bh"]),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile", "activity_factor")
    # ### end Alembic commands ###
