"""Profile is now one-to-one

Revision ID: 948c7c8f64f7
Revises: cbf9d73e39c1
Create Date: 2023-04-18 14:26:36.712898

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '948c7c8f64f7'
down_revision = 'cbf9d73e39c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
