"""Added foreign key relationships

Revision ID: 96583efeb761
Revises: 17ef3d59234c
Create Date: 2023-03-17 09:37:43.857656

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '96583efeb761'
down_revision = '17ef3d59234c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientitem', sa.Column('ingredient_id', sa.Integer(), nullable=True))
    op.add_column('ingredientitem', sa.Column('dish_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingredientitem', 'dish', ['dish_id'], ['id'])
    op.create_foreign_key(None, 'ingredientitem', 'ingredient', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredientitem', type_='foreignkey')
    op.drop_constraint(None, 'ingredientitem', type_='foreignkey')
    op.drop_column('ingredientitem', 'dish_id')
    op.drop_column('ingredientitem', 'ingredient_id')
    # ### end Alembic commands ###
