"""Removed DRI model

Revision ID: a507345d73fb
Revises: aefc20be794c
Create Date: 2023-04-26 08:49:15.394981

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a507345d73fb'
down_revision = 'aefc20be794c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'activity_factor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('activity_factor', postgresql.ENUM('little', 'one_time', 'two_times', 'three_times', 'every_day', 'professional_athlete', name='activityfactor'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
