"""Removed DRI model

Revision ID: aefc20be794c
Revises: af56038e470e
Create Date: 2023-04-25 14:26:10.392957

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'aefc20be794c'
down_revision = 'af56038e470e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
