"""Removed DRI model

Revision ID: af56038e470e
Revises: e3a081a20c22
Create Date: 2023-04-25 14:24:44.085002

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af56038e470e'
down_revision = 'e3a081a20c22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'sex',
               existing_type=postgresql.ENUM('male', 'female', name='sex'),
               nullable=True)
    op.alter_column('profile', 'activity_factor',
               existing_type=postgresql.ENUM('little', 'one_time', 'two_times', 'three_times', 'every_day', 'professional_athlete', name='activityfactor'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'activity_factor',
               existing_type=postgresql.ENUM('little', 'one_time', 'two_times', 'three_times', 'every_day', 'professional_athlete', name='activityfactor'),
               nullable=False)
    op.alter_column('profile', 'sex',
               existing_type=postgresql.ENUM('male', 'female', name='sex'),
               nullable=False)
    # ### end Alembic commands ###
