"""Added dishes

Revision ID: b221abd90c96
Revises: 15c1fbf95356
Create Date: 2023-03-16 13:58:47.372828

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b221abd90c96'
down_revision = '15c1fbf95356'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientitem', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredientitem', 'amount')
    # ### end Alembic commands ###
