"""Created user profile

Revision ID: b3a7f62d05f4
Revises: f1e1b4635344
Create Date: 2023-04-11 14:04:14.186083

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "b3a7f62d05f4"
down_revision = "f1e1b4635344"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint(None, "user", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.alter_column("user", "username", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
