"""Dish ingredient now optional

Revision ID: ca22444c1de5
Revises: b221abd90c96
Create Date: 2023-03-16 14:43:02.800763

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ca22444c1de5'
down_revision = 'b221abd90c96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('dish', sa.Column('recipe', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('dish', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('dish', 'recipe')
    op.drop_column('dish', 'name')
    # ### end Alembic commands ###
