"""Fixed typo

Revision ID: cbf9d73e39c1
Revises: bd73a0ad0266
Create Date: 2023-04-18 13:40:06.377995

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cbf9d73e39c1'
down_revision = 'bd73a0ad0266'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('weight', sa.Integer(), nullable=False))
    op.drop_column('profile', 'wight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('wight', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('profile', 'weight')
    # ### end Alembic commands ###
