"""Removed DRI model

Revision ID: e3a081a20c22
Revises: fe36c00255c3
Create Date: 2023-04-25 14:20:54.675652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e3a081a20c22'
down_revision = 'fe36c00255c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
