"""Extended dish model by servings and prep_time

Revision ID: f6153ccfd2fc
Revises: 6b0b686f3fc2
Create Date: 2026-03-10 19:38:32.069467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6153ccfd2fc'
down_revision: Union[str, Sequence[str], None] = '6b0b686f3fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('dish', sa.Column('prep_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'prep_time')
    op.drop_column('dish', 'servings')
    # ### end Alembic commands ###
