"""Removed DRI model

Revision ID: fe36c00255c3
Revises: 948c7c8f64f7
Create Date: 2023-04-25 14:09:56.910345

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe36c00255c3'
down_revision = '948c7c8f64f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dietaryreferenceintakes')
    op.add_column('profile', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('carbohydrates', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('fat', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('protein', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('fiber', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('potassium', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('sodium', sa.Integer(), nullable=True))
    op.alter_column('profile', 'sex',
               existing_type=postgresql.ENUM('male', 'female', name='sex'),
               nullable=False)
    op.alter_column('profile', 'activity_factor',
               existing_type=postgresql.ENUM('little', 'one_time', 'two_times', 'three_times', 'every_day', 'professional_athlete', name='activityfactor'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'activity_factor',
               existing_type=postgresql.ENUM('little', 'one_time', 'two_times', 'three_times', 'every_day', 'professional_athlete', name='activityfactor'),
               nullable=True)
    op.alter_column('profile', 'sex',
               existing_type=postgresql.ENUM('male', 'female', name='sex'),
               nullable=True)
    op.drop_column('profile', 'sodium')
    op.drop_column('profile', 'potassium')
    op.drop_column('profile', 'fiber')
    op.drop_column('profile', 'protein')
    op.drop_column('profile', 'fat')
    op.drop_column('profile', 'carbohydrates')
    op.drop_column('profile', 'calories')
    op.create_table('dietaryreferenceintakes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carbohydrates', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fat', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protein', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fiber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('potassium', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sodium', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='dietaryreferenceintakes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dietaryreferenceintakes_pkey')
    )
    # ### end Alembic commands ###
